tryber/sd-012-project-trivia-react-redux

- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/components/Button.js
- src/components/Input.js
- src/index.js
- src/pages/Login.js
- src/redux/reducers/index.js
- src/redux/store/index.js
Configurado os pilares do redux, configurado tela de Login e sua logica.
> [ GRUPO-16 ] [ Requisito 01 ]

- src/App.js
- src/pages/Game.js
- src/pages/Login.js
- src/services/fetchToken.js
Requisito 2, criado a requisição e salvamento do token
> [ GRUPO-16 ] [ REQUISITO-02 ]

- src/App.js
- src/pages/Config.jsx
- src/pages/Login.jsx
Cria um botão na tela inicial que leva para a página de configurações.
> [Group 7] - Requisito 3

- src/pages/Game.jsx
- src/pages/Login.jsx
- src/redux/reducers/loginReducer.js
Req 02 - setando token no localStorage e redirecionando para "/game"
> [main-group-20] Req 02

- src/pages/Login.jsx
- src/redux/actions/index.js
- src/redux/fetchs/fetchToken.js
- src/redux/reducers/index.js
- src/redux/reducers/user.js
Criado funcao de fetch para a requisicao de token, salvando no o toke e os dados no local storage e no redux
> [Group 15] Requisito 2 - Requisição de token

- src/components/Loading.js
- src/pages/Login.js
- src/pages/Trivia.js
- src/reducers/trivia.js
> [Grupo 12] [Requisito 5]

- src/components/Header.jsx
- src/pages/Login.jsx
- src/redux/actions/index.js
- src/redux/reducers/player.jsx
- src/redux/reducers/user.jsx
- src/services/api.jsx
Organiza chaves da store, e adiciona fetch de gravatar ao fazer login
> Group 29 store

- src/components/Questions.js
Refatoração da lógica e aplicação.
> [ MAIN-GROUP-16 ] [ REQUISITO-05-REMAKE ]

- src/App.test.js
- src/components/Questions.jsx
adicionado a lógica de estilização após ser respondida a questão. Estilo de borda verde para as corretas e vermelha para as erradas. 
Adicionado a desabilitação dos botões de alternativas após responder uma
> [main-group-20] Requisito 07

- src/components/Answers.js
- src/components/Question.js
- src/helpers/index.js
- src/index.css
> G4 game page - requisito 7

- src/components/Questions.jsx
Adicionado o temporizador 
Adicionado o botão de próxima pergunta
> [main-group-20] Req08 & Req10

- src/actions/index.js
- src/pages/GameScreen.js
- src/reducers/game.js
- src/reducers/user.js
O requisito 4 foi concluido e também já foi feito a requisição da API das perguntas, só falta ser feita a lógica para renderiza-las na tela.
> [Main Group 1] Requisito 4

- src/component/Header.jsx
- src/component/Login.jsx
- src/component/Quest.jsx
> [Stars r9]

- src/components/ButtonNext.js
- src/components/Questions.js
- src/pages/Game.js
Cria botão "Próximo" que só é renderizado após a seleção de alguma das alternativas.
> [ MAIN-GROUP-16 ] [ REQUISITO-10 ]

- src/components/Answers.js
- src/components/Timer.js
> G4 game page - Timer

- src/App.js
- src/components/Trivia.jsx
- src/pages/Feedback.jsx
- src/pages/Login.jsx
Resolve todos os requisitos relacionados a página de Feedback.
> [Group-7] Requisitos 11-12-13-14-15-16

- src/components/GameHeader.jsx
- src/components/Questions.jsx
- src/pages/Login.jsx
> [main-group-20] - Req 9 

- src/components/GameQuestions.js
- src/components/Header.js
- src/pages/Login.js
Implementado o calculo e salvando no localstorage, ainda não passa no teste.
> [Requisito 9] Main group 3

- src/components/Questions.jsx
- src/pages/Feedback.jsx
adicionando logica de mudança de pergunta
> [main-group-20] Req 11

- src/pages/Feedback.jsx
- src/pages/Ranking.jsx
cria redirecionamento de pagina de ranking e para tela inicial
> [main-group-20] Req 16 e 18 

- src/pages/Feedback.js
- src/pages/Game.js
- src/redux/actions/gameActions.js
- src/redux/actions/index.js
- src/redux/actions/types.js
- src/redux/reducers/player.js
> [Grupo 30][Requisito 13/14]

- src/component/RankingList.jsx
- src/pages/Feedback.js
- src/pages/Ranking.js
> [Stars] r17

- src/pages/Game.js
- src/pages/Login.js
Não estava rodando o evaluator do GH, para não mergear antes de testar. Criei outra branch e repassei tudo feito novamente.
Nota: os testes na máquina estão passando.
> [ GRUPO 13 ] Requisito 9 - 2ª tentativa 

- src/components/Question.jsx
- src/pages/Feedback.jsx
- src/pages/Game.jsx
- src/pages/Login.jsx
- src/pages/Settings.jsx
- src/redux/actions/index.js
- src/redux/reducers/game.jsx
- src/services/api.jsx
Adiciona opções de configurações do jogo
> [Group 29] Game Settings

- src/Pages/Game.js
- src/Pages/Ranking.js
> [ Grupo 26 ] - Requisito 17 - Correções
